version: '3.4'

services:
  server:
    image: go-learning-demo
    container_name: "go-learning-demo"
    build: ./
    command: ./app
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_DATABASE=demo_db
    volumes:
      - ./.data/db:/data/db
    ports:
      - "27017:27017"
    command: mongod --logpath=/dev/null